#!/usr/bin/env python3
"""Trains pipeline.models.counter.PeopleCounterCNN on synthetic CSI data
generated by services/replay's scenarios.

Spawns real services/ingest + services/replay subprocesses per recording
(network only — no in-process imports across service boundaries, per
../../../CLAUDE.md) to collect labeled data: each replay scenario name maps
to a people count via SCENARIO_CLASS_LABELS below. This requires
services/replay's "three_people" scenario (added alongside this script,
see services/replay/src/replay/scenarios.yaml) for the 3+ class.

This produces a small, purely-synthetic dataset good for validating the
training/inference mechanics end to end — not a production-grade model.
Real deployment will need real captured CSI data with far more diversity.

Usage:
    pip install -e ".[dev,ml]"
    python scripts/train_counter.py
    python scripts/train_counter.py --seconds-per-recording 30 --recordings-per-scenario 8  # more data

Outputs (under --output-dir, default services/pipeline/checkpoints/):
    counter_best.pt       - best checkpoint (by validation loss), loadable
                             by pipeline.models.counter.load_checkpoint /
                             pipeline.models.counter_inference.CounterInference
    counter_metrics.json  - accuracy, per-class precision/recall/f1, and
                             confusion matrix on the held-out validation set
"""

from __future__ import annotations

import argparse
import json
import socket
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader

from pipeline.features.spectrogram import compute_spectrogram_features
from pipeline.models.counter import CLASS_LABELS, N_CLASSES, PeopleCounterCNN, save_checkpoint
from pipeline.preprocess import hampel_filter, savitzky_golay_smooth, segment_sliding_window
from pipeline.training import (
    SpectrogramDataset,
    classification_report,
    confusion_matrix,
    print_report,
    stratified_split,
    train_model,
)

WIFI_SENSE_ROOT = Path(__file__).resolve().parents[3]
INGEST_SRC = WIFI_SENSE_ROOT / "services" / "ingest" / "src"
REPLAY_SRC = WIFI_SENSE_ROOT / "services" / "replay" / "src"
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parents[1] / "checkpoints"

SCENARIO_CLASS_LABELS: dict[str, int] = {
    "empty_room": 0,
    "one_person_walking": 1,
    "two_people": 2,
    "three_people": 3,
}


# ---------------------------------------------------------------------------
# Data collection: spawn real replay + ingest, record over ZeroMQ
# ---------------------------------------------------------------------------


def _free_port() -> int:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def _spawn(cmd: list[str], *, pythonpath: Path, env: dict) -> subprocess.Popen:
    proc_env = env.copy()
    proc_env["PYTHONPATH"] = str(pythonpath)
    return subprocess.Popen(cmd, env=proc_env, stderr=subprocess.PIPE, text=True)


def _stop(*procs: subprocess.Popen) -> None:
    for proc in procs:
        proc.terminate()
    for proc in procs:
        try:
            proc.wait(timeout=3)
        except subprocess.TimeoutExpired:
            proc.kill()


def collect_recording(scenario: str, seed: int, *, seconds: float, rate_hz: float, env: dict) -> np.ndarray:
    """Run one real-time replay recording of `scenario` through a fresh
    ingest instance; return the collected (n_frames, n_subcarriers)
    amplitude matrix, sorted by sequence_number."""
    import zmq

    udp_port = _free_port()
    csi_pub_port = _free_port()

    ingest_proc = _spawn(
        [
            sys.executable,
            "-m",
            "ingest",
            "--udp-host",
            "127.0.0.1",
            "--udp-port",
            str(udp_port),
            "--pub-host",
            "127.0.0.1",
            "--pub-port",
            str(csi_pub_port),
            "--plot",
            "none",
        ],
        pythonpath=INGEST_SRC,
        env=env,
    )
    time.sleep(1.0)

    ctx = zmq.Context()
    sub = ctx.socket(zmq.SUB)
    sub.connect(f"tcp://127.0.0.1:{csi_pub_port}")
    sub.setsockopt(zmq.SUBSCRIBE, b"csi")
    sub.setsockopt(zmq.RCVTIMEO, 2000)

    replay_proc = _spawn(
        [
            sys.executable,
            "-m",
            "replay",
            "--scenario",
            scenario,
            "--rate",
            str(rate_hz),
            "--target",
            f"localhost:{udp_port}",
            "--seed",
            str(seed),
        ],
        pythonpath=REPLAY_SRC,
        env=env,
    )

    frames: list[dict] = []
    deadline = time.monotonic() + seconds + 3.0  # grace period for startup jitter
    try:
        while time.monotonic() < deadline:
            try:
                _topic, payload = sub.recv_multipart()
            except zmq.Again:
                break
            frames.append(json.loads(payload.decode("utf-8")))
            if len(frames) > 1:
                elapsed_s = (frames[-1]["timestamp_us"] - frames[0]["timestamp_us"]) / 1e6
                if elapsed_s >= seconds:
                    break
    finally:
        sub.close()
        ctx.term()
        _stop(replay_proc, ingest_proc)

    frames.sort(key=lambda f: f["sequence_number"])
    return np.array([f["amplitude"] for f in frames], dtype=np.float64)


# ---------------------------------------------------------------------------
# Feature extraction: raw amplitude -> labeled (spectrogram, label) pairs
# ---------------------------------------------------------------------------


def build_examples(
    amplitude: np.ndarray,
    label: int,
    *,
    sample_rate_hz: float,
    window_s: float,
    stride_s: float,
    hampel_window: int,
    hampel_sigmas: float,
    savgol_window: int,
    savgol_polyorder: int,
    n_components: int,
    nperseg: int,
    noverlap: int | None,
) -> tuple[np.ndarray, np.ndarray]:
    """Preprocess one recording's amplitude matrix, segment it into
    windows, and compute spectrogram features for each — every window from
    this recording gets the same `label`."""
    cleaned = savitzky_golay_smooth(
        hampel_filter(amplitude, window_size=hampel_window, n_sigmas=hampel_sigmas),
        window_length=savgol_window,
        polyorder=savgol_polyorder,
    )
    windows = segment_sliding_window(cleaned, sample_rate_hz=sample_rate_hz, window_s=window_s, stride_s=stride_s)

    features = np.stack(
        [
            compute_spectrogram_features(
                w,
                n_components=n_components,
                sample_rate_hz=sample_rate_hz,
                nperseg=nperseg,
                noverlap=noverlap,
            )
            for w in windows
        ]
    )
    labels = np.full(len(windows), label, dtype=np.int64)
    return features, labels


# ---------------------------------------------------------------------------
# CLI
#
# Train/val split, Dataset, the training loop, and the metrics report are
# shared with scripts/train_har.py via pipeline.training.
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--seconds-per-recording", type=float, default=15.0)
    parser.add_argument("--recordings-per-scenario", type=int, default=4)
    parser.add_argument("--rate-hz", type=float, default=100.0)
    parser.add_argument("--window-s", type=float, default=2.0)
    parser.add_argument("--stride-s", type=float, default=0.5)
    parser.add_argument("--hampel-window", type=int, default=7)
    parser.add_argument("--hampel-sigmas", type=float, default=3.0)
    parser.add_argument("--savgol-window", type=int, default=11)
    parser.add_argument("--savgol-polyorder", type=int, default=3)
    parser.add_argument("--n-components", type=int, default=5, help="PCA/spectrogram channel count")
    parser.add_argument("--nperseg", type=int, default=32)
    parser.add_argument("--noverlap", type=int, default=None)
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--patience", type=int, default=10)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--val-fraction", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    return parser


def main(argv: list[str] | None = None) -> None:
    import os

    args = build_parser().parse_args(argv)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    env = os.environ.copy()

    torch.manual_seed(args.seed)

    print("collecting synthetic data from services/replay scenarios...", file=sys.stderr)
    all_features: list[np.ndarray] = []
    all_labels: list[np.ndarray] = []
    for scenario, label in SCENARIO_CLASS_LABELS.items():
        for recording_idx in range(args.recordings_per_scenario):
            seed = args.seed * 1000 + label * 100 + recording_idx
            print(
                f"  recording {scenario!r} (label={label}) seed={seed} "
                f"({recording_idx + 1}/{args.recordings_per_scenario})...",
                file=sys.stderr,
            )
            amplitude = collect_recording(
                scenario, seed, seconds=args.seconds_per_recording, rate_hz=args.rate_hz, env=env
            )
            if len(amplitude) < round(args.window_s * args.rate_hz):
                print(f"    WARNING: only collected {len(amplitude)} frames, skipping", file=sys.stderr)
                continue
            features, labels = build_examples(
                amplitude,
                label,
                sample_rate_hz=args.rate_hz,
                window_s=args.window_s,
                stride_s=args.stride_s,
                hampel_window=args.hampel_window,
                hampel_sigmas=args.hampel_sigmas,
                savgol_window=args.savgol_window,
                savgol_polyorder=args.savgol_polyorder,
                n_components=args.n_components,
                nperseg=args.nperseg,
                noverlap=args.noverlap,
            )
            print(f"    -> {len(labels)} windows", file=sys.stderr)
            all_features.append(features)
            all_labels.append(labels)

    X = np.concatenate(all_features, axis=0)
    y = np.concatenate(all_labels, axis=0)
    print(f"\ntotal dataset: {len(y)} windows, shape {X.shape[1:]}", file=sys.stderr)
    for label_idx, label_name in enumerate(CLASS_LABELS):
        print(f"  class {label_name}: {int((y == label_idx).sum())} windows", file=sys.stderr)

    train_idx, val_idx = stratified_split(y, args.val_fraction, args.seed)
    train_dataset = SpectrogramDataset(X[train_idx], y[train_idx])
    val_dataset = SpectrogramDataset(X[val_idx], y[val_idx])
    print(f"train: {len(train_dataset)} windows, val: {len(val_dataset)} windows", file=sys.stderr)

    train_loader = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=args.batch_size, shuffle=False)

    device = torch.device(args.device)
    model = PeopleCounterCNN(in_channels=args.n_components, n_classes=N_CLASSES).to(device)

    print("\ntraining...", file=sys.stderr)
    history = train_model(
        model, train_loader, val_loader, epochs=args.epochs, patience=args.patience, lr=args.lr, device=device
    )

    model.eval()
    all_preds, all_true = [], []
    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            logits = model(X_batch.to(device))
            all_preds.append(logits.argmax(dim=1).cpu().numpy())
            all_true.append(y_batch.numpy())
    y_pred = np.concatenate(all_preds)
    y_true = np.concatenate(all_true)

    cm = confusion_matrix(y_true, y_pred, N_CLASSES)
    report = classification_report(cm, CLASS_LABELS)
    report["history"] = history
    print_report(report)

    checkpoint_path = args.output_dir / "counter_best.pt"
    save_checkpoint(
        checkpoint_path,
        model,
        extra={
            "n_components": args.n_components,
            "nperseg": args.nperseg,
            "noverlap": args.noverlap,
            "sample_rate_hz": args.rate_hz,
            "window_s": args.window_s,
            "stride_s": args.stride_s,
        },
    )
    print(f"\nsaved checkpoint to {checkpoint_path}", file=sys.stderr)

    metrics_path = args.output_dir / "counter_metrics.json"
    with open(metrics_path, "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)
    print(f"saved metrics report to {metrics_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
